### ISSUE TITLE
Use findlast instead of findfirstfromlast?

### ISSUE THREAD

**Issue by yezhengkai** [CGRG-lab/GeneralTools.jl#1]
If the purpose of `findfirstfromlast` is to return the index of the last `true` in the Bool array, the same thing can be done with `findlast`.

**Comment by okatsn** [comment]
Yes they do the same work; I wasn't aware of the existence of `findlast` before. Please use `findlast` instead, it is more efficient. The `findfirstfromlast` will be removed in the future.
